let data,busy=false;
const $=id=>document.getElementById(id),num=n=>n.toLocaleString('ko-KR'),size=n=>n>=1e9?(n/1e9).toFixed(2)+' GB':(n/1e6).toFixed(1)+' MB';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'확인 불가';
function render(){
 const jobs=data.jobs, downloaded=jobs.reduce((a,j)=>a+j.downloaded,0),missing=jobs.reduce((a,j)=>a+j.unavailable,0);
 $('totals').innerHTML=[['누적 수신 파일',num(downloaded),'개'],['누적 수신 용량',size(jobs.reduce((a,j)=>a+j.bytes,0)),''],['자료 없음 기록',num(missing),'건'],['예약 시각','매일 19:00','']].map(([l,v,u])=>`<div class="metric"><span>${l}</span><strong>${v}</strong><small>${u}</small></div>`).join('');
 $('jobs').innerHTML=jobs.map(j=>{
 const running=j.task?.state==='Running',disabled=j.task?.state==='Disabled',last=j.history.at(-1),status=running?'실행 중':disabled?'예약 비활성':!j.task?'예약 조회 불가':j.pending?'수집 대기':j.id==='raw'?'담당 구간 처리 종료':'다음 관측 대기';
 return `<article class="job"><div class="jobtop"><div><h2>${j.title}</h2><p class="subtitle">${j.subtitle}</p></div><span class="badge ${disabled||!j.task||j.id==='raw'?'warn':''}">${status}</span></div><div class="numbers"><strong>${num(j.downloaded)}</strong><span>/ ${num(j.expected)}개 대상 · ${size(j.bytes)}</span></div><div class="progress" role="img" aria-label="수신 ${j.downloaded}, 자료 없음 ${j.unavailable}, 미처리 ${j.pending}"><div class="received" style="width:${100*j.downloaded/j.expected}%"></div><div class="missing" style="width:${100*j.unavailable/j.expected}%"></div></div><div class="stats"><span>수신 ${(100*j.downloaded/j.expected).toFixed(1)}%</span><span>자료 없음 ${num(j.unavailable)}</span><span>미처리 ${num(j.pending)}</span></div><p class="reason">${esc(j.reason)}</p><dl><dt>최근 실행</dt><dd>${j.task?when(j.task.lastRun):'예약 조회 불가'}${j.task&&!running?' · 종료 코드 '+j.task.result:''}</dd><dt>최근 실적</dt><dd>${last?last.date+' · 새 파일 '+num(last.files)+'개 · 요청 '+(last.requests===null?'미확인':num(last.requests)+'회'):'기록 없음'}</dd><dt>오늘 실적</dt><dd>${j.today?'새 파일 '+num(j.today.files)+'개 · 요청 '+(j.today.requests??'미확인')+'회':'오늘 실행 기록 없음'}</dd><dt>다음 실행</dt><dd>${j.task?when(j.task.nextRun):'확인 불가'}</dd><dt>최종 수신</dt><dd>${when(j.lastDownload)}</dd><dt>대상 기간</dt><dd>${j.start} ~ ${j.end}</dd><dt>저장 위치</dt><dd>${esc(j.outputDirectory)}</dd></dl></article>`;
 }).join('');
 const open=new Set([...document.querySelectorAll('details[open]')].map(x=>x.id));
 $('records').innerHTML=jobs.map(j=>`<details id="log-${j.id}" ${open.has('log-'+j.id)?'open':''}><summary>${j.title} · 최근 실행 로그</summary><pre>${esc(j.logs.join('\n'))}</pre></details><details id="missing-${j.id}" ${open.has('missing-'+j.id)?'open':''}><summary>${j.title} · 자료 없음 ${num(j.unavailable)}건</summary><p class="note">자료 없음은 수신 완료가 아닙니다. 과거 결측은 자동 재시도하지 않습니다.${j.id==='ndvi'?' 최신 8일 이내 NDVI 결측은 재시도합니다.':''} 표의 관측시각은 UTC, 확인시각은 한국시간입니다.</p><div class="tablewrap"><table><thead><tr><th>관측 항목 (UTC)</th><th>자료 없음 확인시각</th></tr></thead><tbody>${j.missing.map(m=>`<tr><td>${esc(m.key)}</td><td>${when(m.checkedAt)}</td></tr>`).join('')}</tbody></table></div></details>`).join('');
 let progress=document.getElementById('backfill');
 if(!progress){progress=document.createElement('section');progress.id='backfill';progress.className='panel';$('jobs').after(progress);}
 const raw=jobs.find(j=>j.id==='raw');
 progress.innerHTML=`<h2>과거 자료 수집 도달 지점</h2><p class="subtitle">현재 PC 담당: 2026-08-23 → 2024-08-23 · 매일 10~15시(KST), 두 채널</p><div class="tablewrap"><table><thead><tr><th>실제 다운로드일</th><th>그날 도달한 관측일 (과거 방향)</th><th>새 파일</th></tr></thead><tbody>${raw.history.filter(h=>h.oldest).slice(-8).reverse().map(h=>`<tr><td>${h.date}</td><td>${h.oldest.slice(0,4)}-${h.oldest.slice(4,6)}-${h.oldest.slice(6,8)}</td><td>${num(h.files)}개</td></tr>`).join('')}</tbody></table></div><details id="assignment"><summary>이전 자료의 4인 분담 계획 보기 · 수집 현황은 미확인</summary><p class="note">8월 28일에 만든 배포 패키지의 담당 범위입니다. 다른 PC의 실제 실행·완료 여부는 이 화면에 연결되어 있지 않습니다.</p><div class="tablewrap"><table><thead><tr><th>담당</th><th>기간</th><th>진행 상태</th></tr></thead><tbody><tr><td>1번</td><td>2019-07-25 ~ 2020-10-30</td><td>미확인</td></tr><tr><td>2번</td><td>2020-10-31 ~ 2022-02-06</td><td>미확인</td></tr><tr><td>3번</td><td>2022-02-07 ~ 2023-05-16</td><td>미확인</td></tr><tr><td>4번</td><td>2023-05-17 ~ 2024-08-22</td><td>미확인</td></tr></tbody></table></div></details>`;
 if(open.has('assignment'))document.getElementById('assignment').open=true;
 chart();$('updated').textContent='마지막 확인 '+when(data.generatedAt);
 $('error').hidden=!data.scheduler.error;$('error').textContent=data.scheduler.error||'';
}
function chart(){if(!data)return;const jobs=data.jobs.filter(j=>$('filter').value==='all'||j.id===$('filter').value),today=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Seoul'}));
 const points=Array.from({length:14},(_,i)=>{const d=new Date(today);d.setDate(d.getDate()-13+i);const key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');const rows=jobs.map(j=>j.history.find(h=>h.date===key));return {key,n:rows.reduce((a,r)=>a+(r?.files||0),0),missing:rows.every(r=>!r),partial:rows.some(r=>!r)};});
 const max=Math.max(1,...points.map(p=>p.n));$('chart').innerHTML='<div class="chart">'+points.map(p=>`<div class="barcol" title="${p.key}: ${p.missing?'기록 없음':p.n+'개'+(p.partial?' (일부 작업 기록 없음)':'')}"><span>${p.missing?'—':num(p.n)}</span><div class="bar ${p.missing?'empty':''}" style="height:${p.missing?8:Math.max(3,p.n/max*135)}px"></div><span class="date">${p.key.slice(5).replace('-','/')}</span></div>`).join('')+'</div>';
}
async function refresh(){if(busy)return;busy=true;$('refresh').disabled=true;try{const res=await fetch('/api/status',{signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error();data=await res.json();render();}catch{$('error').hidden=false;$('error').textContent='연결이 끊겼거나 기록을 읽지 못했습니다. 표시된 이전 수치는 최신 상태가 아닙니다.';}finally{busy=false;$('refresh').disabled=false;}}
$('refresh').onclick=refresh;$('filter').onchange=chart;setInterval(()=>{if($('auto').checked)refresh();},5000);refresh();
